name: Release Crate

on:
  push:
    tags:
      - "*"
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish Crate
      run: cargo publish --token {{ CRATE_API_KEY }}
      
      
